services:
  celiver:
    image: celiver:latest
    build:
      context: .
      dockerfile: Dockerfile
      args:
        VERSION: 1.0.0
    volumes:
      - .:/app
    environment:
      - PYTHONUNBUFFERED=1
    command: python /app/src/celiver.py
